spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ea_lab_13?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  file:
    name: logs/bank_application.log

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
        exposure:
            include: "*"
  